# Generated by Django 5.0.6 on 2024-07-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_profile_updateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='user',
        ),
    ]
