# Generated by Django 5.0.6 on 2024-07-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profilesupdates_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilesUpdates',
        ),
    ]
