# Generated by Django 5.0.6 on 2024-07-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilesUpdates',
        ),
    ]
