# Generated by Django 5.0.6 on 2024-07-15 05:15

import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=64),
        ),
    ]
