# Generated by Django 5.0.6 on 2024-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
