# Generated by Django 5.0.6 on 2024-07-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default='wQ2mFR0BYXJx3YgYwGTAlqpBwAXRwNs9a5ZAHE7beQKhmS3sIDVw5qjUHkVrk1CQMu7n6vf9uZ9PYWv5tt16qThHuiUyvui18Ccw', max_length=100),
        ),
    ]
