# Generated by Django 5.0.6 on 2024-07-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default='3LnpyNeOouedmQJ1bIisvRdlhZgm2bRx6XWUw0SjUqczXKfrqarpGxBQOlutfb2MRBYTl8IfLZThK79TpxL37v5tL8MNPc7MQXR8', max_length=100),
        ),
    ]
