# Generated by Django 5.0.6 on 2024-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default='4fx2wzyLKdExSwk51JDdEFOWD5yAL7uzGWlzO0K061rS3Wl4MehsbdhNhQLG2k0k8qqWeJGYs7FOFcmiPHh3WJaLN9y4AAwuiT1K', max_length=100),
        ),
    ]
