# Generated by Django 5.0.6 on 2024-07-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default='AIqieZfgkkUBFtB89jthSM0Jl7GRTn8xL7zBOH6sIpRC4T8JrbrWE3Y2v4VME9PpKGIjNSYeKKS8vWiW', max_length=80),
        ),
    ]
