# Generated by Django 5.0.6 on 2024-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default='MGRdDlR2asPBBgfLmx6ZOrGa39SjM6XuErv3d17W6yCHmx3Af1hrICxJU6w85pvrV3SoqlV9aaLoMK38', max_length=80),
        ),
    ]
