# Generated by Django 5.0.6 on 2024-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default='lzx9xdVwfVHdxROE78XK6dNRy3Ns2S3Rw0saeR6yEOPgXbPtNwrVrGkTy60a8IahNL9ms3ISJnsNZ8SX', max_length=80),
        ),
    ]
