# Generated by Django 5.0.6 on 2024-07-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
