# Generated by Django 5.0.6 on 2024-07-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
