# Generated by Django 5.0.6 on 2024-08-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
