# Generated by Django 5.0.6 on 2024-08-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
