# Generated by Django 5.0.6 on 2024-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flower',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
