# Generated by Django 5.0.6 on 2024-09-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
