# Generated by Django 5.0.6 on 2024-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_flower_category_alter_flower_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
