# Generated by Django 5.0.6 on 2024-07-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
