# Generated by Django 5.0.6 on 2024-08-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='flowers.flower'),
            preserve_default=False,
        ),
    ]
