# Generated by Django 5.0.6 on 2024-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_comment_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
