# Generated by Django 5.0.6 on 2024-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0009_alter_flower_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
