# Generated by Django 5.0.6 on 2024-08-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
