# Generated by Django 5.0.6 on 2024-08-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0020_remove_comment_user_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.CharField(default=False),
        ),
    ]
