# Generated by Django 5.0.6 on 2024-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0022_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(upload_to='flowers/images/'),
        ),
    ]
