# Generated by Django 5.0.6 on 2024-07-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_created_on_order_order_date_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.flower'),
        ),
    ]
