# Generated by Django 5.0.6 on 2024-07-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_userprofile_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
